name: game_hub
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4
  go_router: ^12.0.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
